project_id = "petveteu"

[auth]
site_url = "https://petveteu.vercel.app"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://127.0.0.1:3000",
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[functions.reminders]
verify_jwt = false

[functions.admin-clients]
verify_jwt = true

[functions.admin-vets]
verify_jwt = true

[auth.email.template.invite]
subject = "Convite PetVet EU / PetVet EU invitation"
content_path = "./supabase/templates/invite.html"

[auth.email.template.magic_link]
subject = "PetVet EU"
content_path = "./supabase/templates/magic-link.html"
