create extension if not exists pgcrypto;
create type public.user_role as enum ('client','vet');
create type public.app_locale as enum ('pt-PT','en');
create type public.pet_species as enum ('dog','cat','other');
create type public.reminder_status as enum ('pending','submitted','delivered','exhausted','cancelled','permanently_skipped');
create type public.attempt_outcome as enum ('dry_run','submitted','transient_failure','permanent_skip');
create type public.run_status as enum ('running','succeeded','failed');

create table public.profiles(
 id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null default 'client',
 email text not null check(email=lower(trim(email)) and length(email)<=320), full_name text not null check(length(trim(full_name)) between 1 and 120),
 phone text check(phone is null or phone ~ '^\+[1-9][0-9]{7,14}$'), locale public.app_locale not null default 'pt-PT', is_incomplete boolean not null default false,
 sms_enabled_by_client boolean not null default true, sms_enabled_by_vet boolean not null default true, mfa_required boolean not null default false,
 processing_restricted boolean not null default false, legal_hold_until date, created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version bigint not null default 1
);
create unique index profiles_email_unique on public.profiles(lower(email));create unique index profiles_phone_unique on public.profiles(phone) where phone is not null;create unique index one_vet_only on public.profiles(role) where role='vet';

create table public.pets(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id),name text not null check(length(trim(name)) between 1 and 100),species public.pet_species not null,other_species text check(other_species is null or length(trim(other_species)) between 1 and 60),date_of_birth date not null check(date_of_birth<=current_date),birth_date_is_estimated boolean not null default false,breed text check(breed is null or length(trim(breed))<=100),notification_expiry_years int not null check(notification_expiry_years between 1 and 50),deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version bigint not null default 1,check((species='other' and other_species is not null) or (species<>'other' and other_species is null)));
create table public.vaccination_entries(id uuid primary key default gen_random_uuid(),pet_id uuid not null references public.pets(id),vaccine_type text not null check(length(trim(vaccine_type)) between 1 and 120),due_date date not null,last_administered_date date check(last_administered_date is null or (last_administered_date<=due_date and last_administered_date<=current_date)),notes text check(notes is null or length(notes)<=2000),deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version bigint not null default 1);
create unique index active_vaccine_unique on public.vaccination_entries(pet_id,lower(trim(vaccine_type)),due_date) where deleted_at is null;
create table public.reminders(id uuid primary key default gen_random_uuid(),vaccination_entry_id uuid not null references public.vaccination_entries(id),due_date date not null,status public.reminder_status not null default 'pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(vaccination_entry_id,due_date));
create table public.reminder_attempts(id uuid primary key default gen_random_uuid(),reminder_id uuid not null references public.reminders(id),outcome public.attempt_outcome not null,reason_code text check(reason_code is null or length(reason_code)<=80),provider_sid text check(provider_sid is null or length(provider_sid)<=80),created_at timestamptz not null default now(),check((outcome='submitted' and provider_sid is not null) or (outcome<>'submitted' and provider_sid is null)));
create table public.reminder_job_runs(id uuid primary key default gen_random_uuid(),business_date date not null,trigger_source text not null check(trigger_source in ('scheduled','manual')),status public.run_status not null default 'running',started_at timestamptz not null default now(),completed_at timestamptz,error_code text check(error_code is null or length(error_code)<=80));
create unique index one_run_per_date on public.reminder_job_runs(business_date) where status in ('running','succeeded');
create table public.admin_audit_events(id uuid primary key default gen_random_uuid(),actor_id uuid references public.profiles(id),target_id uuid,action text not null check(length(action)<=80),details jsonb not null default '{}' check(pg_column_size(details)<=4096),created_at timestamptz not null default now());
create table public.data_subject_requests(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id),request_type text not null check(request_type in ('access','correction','objection','restriction','erasure')),verified_at timestamptz,outcome text check(outcome is null or length(outcome)<=120),retention_basis text check(retention_basis is null or length(retention_basis)<=240),completed_at timestamptz,created_at timestamptz not null default now());

create function public.touch_version() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();new.version=old.version+1;return new;end$$;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_version();create trigger pets_touch before update on public.pets for each row execute function public.touch_version();create trigger vaccine_touch before update on public.vaccination_entries for each row execute function public.touch_version();
create function public.auth_profile_sync() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,email,full_name,phone,locale,is_incomplete) values(new.id,lower(trim(new.email)),coalesce(nullif(trim(new.raw_user_meta_data->>'full_name'),''),'Cliente'),nullif(new.raw_user_meta_data->>'phone',''),coalesce((new.raw_user_meta_data->>'locale')::public.app_locale,'pt-PT'),new.raw_user_meta_data->>'phone' is null) on conflict(id) do update set email=excluded.email;return new;end$$;
create trigger auth_profile_insert after insert on auth.users for each row execute function public.auth_profile_sync();create trigger auth_email_sync after update of email on auth.users for each row when(old.email is distinct from new.email) execute function public.auth_profile_sync();
create function public.is_vet() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and role='vet')$$;

alter table public.profiles enable row level security;alter table public.pets enable row level security;alter table public.vaccination_entries enable row level security;alter table public.reminders enable row level security;alter table public.reminder_attempts enable row level security;alter table public.reminder_job_runs enable row level security;alter table public.admin_audit_events enable row level security;alter table public.data_subject_requests enable row level security;
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_vet());
create policy pet_read on public.pets for select to authenticated using(deleted_at is null and(owner_id=auth.uid() or public.is_vet()));
create policy vaccine_read on public.vaccination_entries for select to authenticated using(deleted_at is null and exists(select 1 from public.pets p where p.id=pet_id and p.deleted_at is null and(p.owner_id=auth.uid() or public.is_vet())));
create policy reminder_read on public.reminders for select to authenticated using(exists(select 1 from public.vaccination_entries v join public.pets p on p.id=v.pet_id where v.id=vaccination_entry_id and(p.owner_id=auth.uid() or public.is_vet())));
create policy attempt_read on public.reminder_attempts for select to authenticated using(exists(select 1 from public.reminders r join public.vaccination_entries v on v.id=r.vaccination_entry_id join public.pets p on p.id=v.pet_id where r.id=reminder_id and(p.owner_id=auth.uid() or public.is_vet())));
create policy vet_runs on public.reminder_job_runs for select to authenticated using(public.is_vet());create policy vet_audit on public.admin_audit_events for select to authenticated using(public.is_vet());create policy own_requests on public.data_subject_requests for select to authenticated using(profile_id=auth.uid() or public.is_vet());
revoke all on all tables in schema public from anon,authenticated;grant select on public.profiles,public.pets,public.vaccination_entries,public.reminders,public.reminder_attempts,public.reminder_job_runs,public.admin_audit_events,public.data_subject_requests to authenticated;

create function public.update_my_profile(p_full_name text,p_phone text,p_locale public.app_locale,p_sms boolean,p_version bigint) returns public.profiles language plpgsql security definer set search_path='' as $$declare r public.profiles;begin update public.profiles set full_name=trim(p_full_name),phone=p_phone,locale=p_locale,sms_enabled_by_client=p_sms where id=auth.uid() and role='client' and version=p_version returning * into r;if r.id is null then raise exception 'stale_or_forbidden';end if;return r;end$$;
create function public.client_create_pet(p_name text,p_species public.pet_species,p_other_species text,p_birth date,p_estimated boolean,p_breed text) returns public.pets language plpgsql security definer set search_path='' as $$declare r public.pets;begin if not exists(select 1 from public.profiles where id=auth.uid() and role='client') then raise exception 'forbidden';end if;insert into public.pets(owner_id,name,species,other_species,date_of_birth,birth_date_is_estimated,breed,notification_expiry_years) values(auth.uid(),trim(p_name),p_species,nullif(trim(p_other_species),''),p_birth,p_estimated,nullif(trim(p_breed),''),case p_species when 'dog' then 12 when 'cat' then 15 else 10 end) returning * into r;return r;end$$;
create function public.update_pet(p_id uuid,p_name text,p_species public.pet_species,p_other_species text,p_birth date,p_estimated boolean,p_breed text,p_expiry int,p_version bigint) returns public.pets language plpgsql security definer set search_path='' as $$declare r public.pets;begin update public.pets set name=trim(p_name),species=p_species,other_species=nullif(trim(p_other_species),''),date_of_birth=p_birth,birth_date_is_estimated=p_estimated,breed=nullif(trim(p_breed),''),notification_expiry_years=case when public.is_vet() then p_expiry else notification_expiry_years end where id=p_id and deleted_at is null and version=p_version and(owner_id=auth.uid() or public.is_vet()) returning * into r;if r.id is null then raise exception 'stale_or_forbidden';end if;return r;end$$;
create function public.remove_pet(p_id uuid,p_version bigint) returns void language plpgsql security definer set search_path='' as $$begin update public.pets set deleted_at=now() where id=p_id and deleted_at is null and version=p_version and(owner_id=auth.uid() or public.is_vet());if not found then raise exception 'stale_or_forbidden';end if;update public.reminders r set status='cancelled' from public.vaccination_entries v where v.pet_id=p_id and r.vaccination_entry_id=v.id and r.status='pending';end$$;
create function public.vet_update_client(p_id uuid,p_name text,p_phone text,p_locale public.app_locale,p_sms boolean,p_version bigint) returns public.profiles language plpgsql security definer set search_path='' as $$declare r public.profiles;begin if not public.is_vet() then raise exception 'forbidden';end if;update public.profiles set full_name=trim(p_name),phone=p_phone,locale=p_locale,sms_enabled_by_vet=p_sms,is_incomplete=p_phone is null where id=p_id and role='client' and version=p_version returning * into r;if r.id is null then raise exception 'stale_or_forbidden';end if;return r;end$$;
create function public.vet_save_vaccination(p_id uuid,p_pet_id uuid,p_type text,p_due date,p_admin date,p_notes text,p_version bigint) returns public.vaccination_entries language plpgsql security definer set search_path='' as $$declare r public.vaccination_entries;old_due date;begin if not public.is_vet() then raise exception 'forbidden';end if;if p_id is null then insert into public.vaccination_entries(pet_id,vaccine_type,due_date,last_administered_date,notes) values(p_pet_id,trim(p_type),p_due,p_admin,nullif(trim(p_notes),'')) returning * into r;else select due_date into old_due from public.vaccination_entries where id=p_id and version=p_version and deleted_at is null for update;if old_due is null then raise exception 'stale_or_forbidden';end if;update public.vaccination_entries set vaccine_type=trim(p_type),due_date=p_due,last_administered_date=p_admin,notes=nullif(trim(p_notes),'') where id=p_id returning * into r;if old_due<>p_due then update public.reminders set status='cancelled' where vaccination_entry_id=p_id and due_date=old_due and status='pending';end if;end if;return r;end$$;
create function public.vet_remove_vaccination(p_id uuid,p_version bigint) returns void language plpgsql security definer set search_path='' as $$begin if not public.is_vet() then raise exception 'forbidden';end if;update public.vaccination_entries set deleted_at=now() where id=p_id and version=p_version and deleted_at is null;if not found then raise exception 'stale_or_forbidden';end if;update public.reminders set status='cancelled' where vaccination_entry_id=p_id and status='pending';end$$;
revoke all on all functions in schema public from public,anon,authenticated;grant execute on function public.is_vet(),public.update_my_profile(text,text,public.app_locale,boolean,bigint),public.client_create_pet(text,public.pet_species,text,date,boolean,text),public.update_pet(uuid,text,public.pet_species,text,date,boolean,text,int,bigint),public.remove_pet(uuid,bigint),public.vet_update_client(uuid,text,text,public.app_locale,boolean,bigint),public.vet_save_vaccination(uuid,uuid,text,date,date,text,bigint),public.vet_remove_vaccination(uuid,bigint) to authenticated;
